# Generated by Django 4.2.2 on 2023-06-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.TextField()),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
