# Generated by Django 4.2.2 on 2023-07-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_author_book_userprofile_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='books',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
