# Generated by Django 4.2.2 on 2023-07-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_check_loan_eligibility_delete_loanapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=10)),
                ('Married', models.CharField(max_length=20)),
                ('Dependents', models.CharField(max_length=50)),
                ('Education', models.CharField(max_length=20)),
                ('Self_Employed', models.CharField(max_length=26)),
                ('ApplicantIncome', models.FloatField()),
                ('CoapplicantIncome', models.FloatField()),
                ('LoanAmount', models.FloatField()),
                ('Loan_Amount_Term', models.IntegerField()),
                ('Credit_History', models.FloatField()),
                ('Property_Area', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Check_loan_eligibility',
        ),
    ]
