# Generated by Django 4.2.2 on 2023-07-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_loan_application_delete_check_loan_eligibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_application',
            name='Married',
        ),
    ]
