# Generated by Django 4.2.2 on 2023-07-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_loan_application_property_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_application',
            name='Gender',
            field=models.CharField(choices=[(0, 'MALE'), (1, 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loan_application',
            name='Property_Area',
            field=models.CharField(max_length=50),
        ),
    ]
