# Generated by Django 4.2.2 on 2023-08-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_loan_application_credit_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_application',
            name='Credit_History',
            field=models.FloatField(choices=[(0, 'Yes'), (1, 'No')]),
        ),
    ]
