# Generated by Django 4.2.2 on 2023-08-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_loan_application_credit_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
